// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Default Suite', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('clickingAllButtons', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1200, height: 770 })
    vars["windowHandles"] = await driver.getAllWindowHandles()
    await driver.findElement(By.linkText("Google Link")).click()
    vars["win2723"] = await waitForWindow(2000)
    vars["root"] = await driver.getWindowHandle()
    await driver.switchTo().window(vars["win2723"])
    await driver.switchTo().window(vars["root"])
    vars["windowHandles"] = await driver.getAllWindowHandles()
    await driver.findElement(By.linkText("Bing Link")).click()
    vars["win8163"] = await waitForWindow(2000)
    await driver.switchTo().window(vars["win8163"])
    await driver.switchTo().window(vars["root"])
    vars["windowHandles"] = await driver.getAllWindowHandles()
    await driver.findElement(By.linkText("Duckduckgo Link")).click()
    vars["win9043"] = await waitForWindow(2000)
    await driver.switchTo().window(vars["win9043"])
    await driver.switchTo().window(vars["root"])
    await driver.findElement(By.linkText("Goes Nowhere")).click()
    await driver.switchTo().window(vars["win9043"])
    await driver.close()
    await driver.switchTo().window(vars["root"])
    await driver.switchTo().window(vars["win8163"])
    await driver.close()
    await driver.switchTo().window(vars["root"])
    await driver.switchTo().window(vars["win2723"])
    await driver.close()
    await driver.switchTo().window(vars["root"])
    await driver.findElement(By.css(".btn-primary")).click()
    vars["windowHandles"] = await driver.getAllWindowHandles()
    await driver.findElement(By.css(".btn-info")).click()
    vars["win2501"] = await waitForWindow(2000)
    await driver.switchTo().window(vars["win2501"])
    await driver.switchTo().window(vars["root"])
    await driver.switchTo().window(vars["win2501"])
    await driver.close()
    await driver.switchTo().window(vars["root"])
    await driver.findElement(By.css("button:nth-child(9)")).click()
  })
})
